export const customers = [
    {
    code: '001',
    name: "Mohammed",
    country: 'KSA',
    job:'Accountant',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '002',
    name: "Ibrahim",
    country: 'KSA',
    job:'Cashier',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '003',
    name: "Abbas",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '004',
    name: "Ali",
    country: 'KSA',
    job:'HR',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '005',
    name: "Ali Hamed",
    country: 'Egypt',
    job:'HR',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '006',
    name: "Khaled Hamed",
    country: 'Egypt',
    job:'Accountant',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '007',
    name: "Mai Hamed",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '008',
    name: "Sameh Kamel",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '008',
    name: "Sameh Kamel",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '008',
    name: "Sameh Kamel",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '011',
    name: "Kareem",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '011',
    name: "Kareem",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '011',
    name: "Kareem",
    country: 'Egypt',
    job:'Driver',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Saleh",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Elsayed",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Mohammed",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Ahmed",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '019',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '014',
    name: "Salman",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'/img/profile.jpg',
    edit:'',
    delete:'',
},
];