export const customers = [
    {
    code: '001',
    name: "Mohammed",
    country: 'KSA',
    job:'Accountant',
    phone:'01234567891',
    image:'https://i.ibb.co/DMCn29T/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '002',
    name: "Ibrahim",
    country: 'KSA',
    job:'Cashier',
    phone:'01234567891',
    image:'https://i.ibb.co/DMCn29T/profile.jpg',
    edit:'',
    delete:'',
},
    {
    code: '003',
    name: "Abbas",
    country: 'KSA',
    job:'Manager',
    phone:'01234567891',
    image:'https://i.ibb.co/DMCn29T/profile.jpg',
    edit:'faCoffee',
    delete:'',
},
    {
    code: '004',
    name: "Ali",
    country: 'KSA',
    job:'HR',
    phone:'01234567891',
    image:'https://i.ibb.co/DMCn29T/profile.jpg',
    edit:'',
    delete:'',
},
];